### PR TITLE
Added PHP 8.3 to the list of build envs

### PR DESCRIPTION
**Pull request by fezfez**

### CODE REVIEW

**Comment by fezfez** [comment]
ping @weierophinney :)

**Comment by weierophinney** [comment]
:+1:

**Comment by sasezaki** [comment]
@weierophinney 

Could you please release for this ?

I've got this error...
```
 docker run -v $(realpath .):/github/workspace -w=/github/workspace ghcr.io/laminas/laminas-continuous-integration:1 \
 '{"php":"8.3","dependencies":"lowest","extensions":[], "extensions":["swoole"], "ini":["memory_limit=-1"],"command":"markdownlint README.md"}'
Received job: {"php":"8.3","dependencies":"lowest","extensions":[], "extensions":["swoole"], "ini":["memory_limit=-1"],"command":"markdownlint README.md"}
Marking PHP 8.3 as configured default
Fetching swoole extension package for PHP 8.3
--2024-06-11 12:36:49--  https://github.com/weierophinney/laminas-ci-swoole-builder/releases/download/0.2.2/php8.3-swoole.tgz
Resolving github.com (github.com)... ::ffff:20.27.177.113, 20.27.177.113
Connecting to github.com (github.com)|::ffff:20.27.177.113|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-06-11 12:36:49 ERROR 404: Not Found.
```

**Comment by sasezaki** [comment]
> Could` you please release for this ?

oops.sorry, I didn' t notice there were problem PHP 8.3 compatible build in Nov 2023.

**Pull request merged**
